version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    ports: 
      - "5433:5433"
    environment: 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: menu_planner
    volumes:
      - ./postgres:/var/lib/postgresql/data